---
title: "Mental Health in the Workplace"
author: "Rosemary Adams, Jessica Libman, Calvin Korver and Anushree Shukla   "
date: "3/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
```

##Abstract
This paper details the strategy our group took to solve the question of what factors most influence the social acceptance of mental health in the work place, and what can we do based on those findings. We developed three metrics to evaluate this question - social acceptance, each of communication and ease of access. We used logarithmic regression to evaluate the significance of different combinations of covariates for each outcome. To do this we built an interactive tool where you could build a model, see the p values of each covariate, and the goodness of fit of the model. Ultimately we can conclude that having open conversations about mental health in the abstract, allowing those who are suffering from it to remain anonymous if they choose, and allowing for leave to be taken to recover from mental illness are going to have the most impact in increasing the social acceptance of mental health.   

##Introduction

The problem space we are exploring in this paper is the significance of the social acceptance of mental health, and how that interacts with measures like ease of communication about mental health and ease of access to resources about mental health. This is significant because in a given year, typically one in five people in the USA alone will suffer from mental illness (5). It is an extremely prevalent form of human suffering that carries a much higher stigma against it than physically apparent injuries and illnesses, such as broken bones or cancer. As such, society in the USA is much less inclined to give those suffering from mental illness the sort of leeway for recovery that they would for physical illnesses. This is apparent in insurance claims, company policies on leave, and even down to a low level employee's direct supervisor. So the purpose of this exploration is to use the data we have to identify signifcant factors of work life that impact the social acceptance, ease of access and ease of communication one experiences in the work place, and then take those factors and make concrete recommendations that employers can use to make their offices more accessible to those with mental illness. Our specific question of interest is   

####To what extent do different facets of interactions about mental health in the office contribute to the social acceptance of mental health?

The data in this analysis comes from a survey conducted by Open Sourcing Mental Illness (OSMI) a non profit corporation dedicated to raising awareness, educating, and providing resources to support mental wellness in the tech and open source communities. They do a survey annually, and we are using the 2014 survey for this project. The survey contained demographic information about the participant, and the answers to their questions from the survey. 

##Related Work - A description of previous papers or projects related to your project.
The study and impact of mental health awareness has been particularly prevalent in the last couple of years and many researchers have found it interesting to study the associations between common mental disorders and workplace productivity. “Mental health and the workplace: issues for developing countries”, a paper that highlights the necessity of providing mental health benefits and leniency towards those who need days off in developing countries. While developed countries like the US do a good job at addressing mental health concerns, its other places in the world that need to be taught how to motivate and encourage their employees to be comfortable enough to talk about anxiety, stress and other depressive conditions that are increasingly common in high-pressure environments. Supporting research in this paper suggest that “the odds of absenteeism due to health reasons [are] twice as high for employees with depressive symptoms.” Therefore it is important to highlight the direct correlation of employee well-being to overall productivity. Other papers, like “The Work of the Workplace Mental Health” have similarly studied and investigated the impacts of productivity in the workplace. This ethnographic study based in Ontario, looked at “(1) employees’ work of managing and negotiating episodes of depression, (2) managers’ administrative work of maintaining privacy and confidentiality, and (3) the administrative work of authorizing illness.” The lack of awareness and inadequate training to provide mental health support is one of the reasons why many workplaces fail to establish a socially acceptable 

We discuss three institutionally organized processes that play a dominant role in coordinating the experiences of employees with self-reported depression: We shed light on how confidential medicalized disability management programs render managers ill prepared and inadequately trained to provide mental health support to their employees. Our findings inform advocacy efforts and facilitate both organizational and policy change to enhance services and supports for employees.


##Methods - A detailed explanation of the techniques and algorithms you used to solve the problem.

###Data Cleaning
When we originally procured the data, the first thing we did was trim responses out to just the ones we needed. There was an area for comments by the respondant that we removed, and we also removed country and state level data because of the large number of non responses. We had hoped to continue using age as a covaritate, but there were also a large number of non responses as well as responses that didn't make sense (extremely high numbers, negative values, and extremely small numbers).

We then went about encoding all of the remaining responses into numeric values. We did this so we could easily calculate our outcomes of interest and run regressions of the data (See Figure 1).

We also decided to coerce some responses. These desicions were context based, for example, there were NA responses to the 'Are you self employed?' question. Because there were only about 10 non responses, we determined that these respondants were NOT self employed, because they indicated working at large companies in the 'How many employees does your company have?' question. Some questions, for example, 'Has your employer ever discussed mental health as part of an employee wellness program?' had the responses of 'yes', 'no', and 'don't know'. Due to the nature of the question, we were able to encode the 'dont' know' responses as 'no' responses, because if you had never experienced a mental health dicussion then your response could equally be no or don't know.

Finally, we were able to split our original dataset into two subsets for exploration. One of the questions in the survey that stood out to us was 'If you have a mental illness, to what extent would you say it has interfered with your work?' We found this interesting because no where in the survey does it ask directly if a participant has a mental illness, but this question is prety revealing. If one answered it, they likely had a mental illness, and this allowed us to split the set into those who were suffering from mental illness and those who were not.

###Calculating the Outcomes of Interest

We calculated a binary outcome to represent the social acceptance, ease of communication, and ease of acccess for mental health in the workplace (See Figure 2). If a response contained certain responses that it was categorized as having the outcome, and if it failed on any one of the responses we were looking at, it was categorized as not having that outcome. This simple approach was taken in order to allow us to consider all three outcomes without using wildly different methods of arriving at those outcomes, so we could compare our results of those models.

###The Model

For this project we decided to do a log regression on several combinations of covariates for each outcome of interest, using the full dataset as our background for data. We decided not to use the subsets of having a mental illness vs not having a mental illness because our recommendatoins shoudl work for all employees, because those who do not have an illness now might develop one later, and those suffering now may not need the resources forever. For this analysis it was not critical for us to select a p value threshold because we were looking at the effects of both singular covariates as well as combinations, but we did generally tend towards values below 0.05. In addition to examining the relative values of the p values we also checked the goodness of fit of the model on an ROC curve. Our final model choices were based on a combination of contextual choices (what covariates intuitively work well together), the goodness of fit of the ROC curve, and then the resulting p values from the model.

###The Technique

As stated previously, our final models of choice relied on several factors, including context. This meant that instead of streamlining the process of finding the lowest p value combinations/best ROC curve fit for each outcome of interest by writing a program to do it, we decided to work through combinations by hand and consider the implications of each. For example, gender seemed to have a large influence on the outcome of interest, but we couldn't very well suggest that each office become entirely female. Our goal was to provide concrete recommendations based on the data, and for us that required taking context into consideration for each covariate. This meant that we developed a tool to explore the data, the p values and the goodness of fit of the model. You can see a screenshot of the tool in Figure 3, and look at the site here. 

##Results - The major insights resulting from your research.

The following results are the covariates of interest that we found for each outcome considered in this paper. Their respective charts can be found in the appendix.

[[[ALSO going to put in figure references]]]

###Ease of Communication

Family_history, leave, and seek_help have the biggest effect on our outcome of interest, ease of communication. The p-values for these covariates range from essentially 0 to 389mu, which is also essentially 0. This shows a very strong correlation. After finding these covariates of interest, we are able to speculate about why they have an effect on ease of communication. The questions asked were "Do you have a family history of mental illness?", "How easy is it for you to take medical leave for a mental health condition?", and "Does your employer provide resources to learn more about mental health issues and how to seek help?". These questions seem to be fairly intuitive in the relation to ease of communication - perhaps because the subject has family history of mental health ilness, they know of resoures and feel more comfortable discussing the fact. Additionally, if an employer provides mental health resources and it is easy to take medical leave because of a mental health condition, the subject may become more common and less personal in the workplace, allowing the subject to talk freely about mental health.

###Ease of Access

Treatment, no_employee, and anonymity have the biggest effect on our outcome of interest, ease of access to mental health care. The p-values for these covariates range from essentially 0 to 0.027, which show a strong correlation. The questions asked were "Have you sought treatment for a mental health condition?", "How many employees does your company or organization have?", and "Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources?". Some of these questions intuitivly make sense immediately - anonymity provides privacy and so subjects may feel safer to access mental health care. If the subject has already sought treatment for a mental health condition, they will be more familiar with attaining the help they desire. Number of employees seems the least related to accessing mental health care, but perhaps in a large company, the subject knows more people who have used mental health services and then better understands the opportunities to gain access to mental health care. On the other hand, if the subject works at a small company, they may be closer with the other employees and have a more diverse dialogue that includes the subject of mental health.

###Social Acceptance

Coworkers, leave, supervisor, and obs_consequence have the biggest effect on our outcome of interest, social acceptance of mental health care. The p-values for these covariates range from essentially 0 to 0.98 (observed consequence). This is an extremely high p-value, but it is important to notice that when the observed consequence is selected as a covariate, the other covariate's p-values decrease significantly - the next highest is coworkers at 0.48. It is likely so high because we used it in our calculation of social acceptance. The questions asked were "Would you be willing to discuss a mental health issue with your coworkers?", "How easy is it for you to take medical leave for a mental health condition?", "Would you be willing to discuss a mental health issue with your direct supervisor(s)?" and "Have you heard of or observed negative consequences for coworkers with mental health conditions in your workplace?". The covariates of coworker and supervisor are very relevent to this outcome because they represent the social aspect of the office. Leave plays a role because the coworkers are willing to fill in for the work you are missing because they understand and accept the needs of mental health conditions. Observed consequence is relevent because it also has to do with the social aspect of the work environment.

##Discussion - What are the implications of your results?

[[[[[request for editing - please remove redundant covariate/question the covariate represents that is in both results and discussion]]]]]

In our 'Ease of Communication' analysis, we found that three covariates `family_history`, `leave`, and `seek_help` had the greatest effect on our outcome of interest. `seek_help` is the most obvious outcome, where subjects answered, 'Does your employer provide resources to learn more about mental health issues and how to seek help?'. Perhaps more interesting was the the correlation between ease of communication and the covariate `family history`, which asks, 'Do you have a family history of mental illness?' In other words, if an employee has a family history of mental illness, they are likelier to find that communicating mental illness is substantially easier. While it is obviously not possible to suggest that employee's should have a family history of mental illness just to improve their ease of communication, we can potentially devise other ways to link these covariates. While providing resources that address mental illnesses and as well as employee health leave are appropriate reponses, we suggest a hybrid of help resources and family mental illness history changes. Specifically, the employer could introduce material that introduces information about family mental illness history and awareness could prove effective in easing the communication of said illnesses. Digital media, documentation, and other sources suggesting employees look into family health history combined with strategica resources for those seeking mental illness help would be an example of this workplace improvement. Ultimately, this solution can be thought of as a combination of covariates that not only informs employees but also provides awareness of family mental health history and acceptance.

When analyzing our covariates for 'Ease of Access', we found that `treatment`, `no_employee` and `anonymity` have the biggest effect. Anonymity had a surprisingly large effect on the outcome of interest and we surmise that because employees have anonymity, they might find it more comfortable or even safer to access mental health care resources. Additionally, an increase in company size also correlates to ease of access - presumably because with more employees, the chance of others knowing about the employees mental health illness decreases. We are led to believe that there is a stigma in the workplace against illness - specifically mental illness. While we could suggest the implementation of measures to anonymize employee requests for mental health illness resources, it still would not solve the problem for companies with a small number of employees (eg. less than 20). Therefore, our recommendation is for companies to not only anonymize the process of seeking access to mental health care and substance abuse treatment, but also to delegate the response to a third-party, like human resources. Many very small companies often utilize a third-party HR resource, which could offer employees an anonymous experience but also simulate a large company because there is less personal health discolsure between HR and other members of the company.

Finally, our last recommendation for improving workplace mental health is concerned with the outcome of interest, 'Social Acceptance'. We found that the covariates, `coworkers`, `supervisor`, `leave`, and `obs_consequence` has the greatest effects. While the first two recommendations above would potentially provide improvements in this outcome of interest as well, we are more concerned with the social impacts of having a mental illness in the workplace. Therefore, we recommend that employers encourage employees to take leave to tend to their mental health illness and promote communication between the coworkers and supervisors about mental health conditions in order to normalize the dialogue about mental health conditions.Coupled with a policy of anonymization and the third-party approval system outlined in recommendation two, this would have significant positive impacts on social acceptance of mental health illness in the workplace.

##Future Work - A description of how your system could be extended.

Our system

##Works Cited

1 https://www.nami.org/learn-more/mental-health-by-the-numbers 
(anushrees source?) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2649890/ 

##Appendix

figure 1 is going to be the table of encodings from our site
figure 2 is going to be our tables showing the outcome of interest "formula"
figure 3 is going to be a screenshot of the interactive tool